### ISSUE TITLE
Rebase of waterfall

### ISSUE THREAD

**Issue by Techcable** [minotopiame/FlexPipe#3]
Most of your patches are already in waterfall, so i'd suggest rebasing of them.

**Comment by Janmm14** [comment]
The initial reason why patches are used is for having a higher possibility that no interaction is needed to be compatible to latest upstream updates.
Next reason for patches is to clearly see what changed in relation to upstream.

The usage of Waterfall as base stops these abilities due to forced delay and it having way too much commits (sometimes w/o any proper description).

It would also require a fairly bit of work to fix the rebase conflicts due to changes in code style, indentiations and 1.7 compability.

(If your initial issue is about crediting, please state so, I can mention you in the readme)

**Comment by Techcable** [comment]
Well we update very often.
In fact, just as much interaction is needed to update waterfall's upstream as it does to update yours. (0 if there are no conflicts)
Its okay if you don't want too, just trying to help.

**Comment by Janmm14** [comment]
Yeah its right you update fast, however if nothing conflicts, FlexPipe is instant without any interaction required. Thanks for the suggestion, but I want to stay with BungeeCord as upstream, because of the other things mentioned.
